//! Web Component code generator.
//!
//! Every generated custom element is style-isolated (FR-VEN-018): it
//! attaches an open shadow root and delivers its CSS through
//! `shadowRoot.adoptedStyleSheets`. The generated code never injects a
//! page-global `<style>` or `<link>` and never reads the host page's
//! stylesheets, so a preview neither leaks styles into the host page nor
//! absorbs conflicting global CSS from it.
//!
//! The sheet adopted is the rafters documentation sheet, WHOLE (issue #105).
//! It is emitted ONCE as [`PREVIEW_STYLES_MODULE`] and imported by every
//! preview, never inlined per component: the sheet is several megabytes, so
//! one copy per preview would be two orders of magnitude more output than the
//! rest of the substrate combined. "Adopt whole" is a statement about the
//! shadow root, not about emission.
//!
//! Why the sheet is adopted rather than subsetted: it carries its tokens on
//! `:host`, and a `:host` declaration in an adopted constructable stylesheet
//! applies to the host element directly, which beats anything inherited from
//! the document `:root`. That is what makes a preview render identically
//! regardless of the host page's theme -- the entire reason previews live in
//! a shadow root.

use crate::rafters_source::DOCUMENTATION_SHEET_PATH;
use crate::react::ComponentStructure;
use crate::traits::{TransformError, TransformedBlock};

/// File name of the shared module every preview imports its sheet from.
/// Written once per output directory beside the pages.
pub const PREVIEW_STYLES_MODULE: &str = "preview-styles.js";

/// Assemble the full transform result for a component structure: the
/// generated Web Component plus the classes and attributes the structure
/// declares. The single assembly point for structure-based previews.
///
/// The preview carries no CSS of its own -- it imports the shared sheet
/// module. Production callers go through [`preview_web_component_block`],
/// which enforces the no-silently-unstyled-preview contract (FR-VEN-018)
/// before a block is assembled at all.
pub fn web_component_block(tag_name: &str, structure: &ComponentStructure) -> TransformedBlock {
    TransformedBlock {
        web_component: generate_web_component(tag_name, structure),
        tag_name: tag_name.to_string(),
        // Still recorded: the class list is docs data (it is what the page
        // reports the component resolves to), even though it no longer
        // drives any CSS selection.
        classes_used: structure.collect_all_classes(),
        attributes: structure.observed_attributes.clone(),
    }
}

/// Assemble a transform result for a preview that will adopt the project's
/// documentation sheet.
///
/// The sheet is not consulted for content -- it is adopted whole at runtime,
/// so there is nothing to match and nothing to fail to match. What IS checked
/// is that a sheet exists at all: a missing or empty sheet is a
/// [`TransformError::RenderFailed`] naming the component and the path,
/// because the alternative is a preview that renders silently unstyled and
/// reads as a design choice rather than a failure.
pub fn preview_web_component_block(
    tag_name: &str,
    structure: &ComponentStructure,
    full_css: &str,
) -> Result<TransformedBlock, TransformError> {
    ensure_sheet_present(&structure.name, full_css)?;
    Ok(web_component_block(tag_name, structure))
}

/// Refuse when the project has no usable preview sheet. Present-but-empty is
/// refused alongside absent: an empty file is the shape a broken regenerate
/// leaves behind, and it would otherwise mark every item documented with no
/// styles -- a green that means the opposite of what it reads as.
pub fn ensure_sheet_present(component: &str, full_css: &str) -> Result<(), TransformError> {
    if full_css.trim().is_empty() {
        return Err(TransformError::RenderFailed {
            component: component.to_string(),
            reason: format!(
                "the rafters preview sheet ({DOCUMENTATION_SHEET_PATH}) is missing or empty; \
                 refusing to emit a preview that would render silently unstyled"
            ),
        });
    }
    Ok(())
}

/// Emit the shared preview sheet module: the documentation sheet verbatim,
/// as one lazily-constructed `CSSStyleSheet` every preview adopts.
///
/// One module, one copy, one `CSSStyleSheet` instance shared across every
/// preview on the page. Construction is deferred to first use so the module
/// also loads where constructable stylesheets are unavailable (for example
/// SSR), and the sheet text is emitted verbatim -- veneer authors no CSS and
/// rewrites none.
pub fn preview_styles_module(full_css: &str) -> String {
    format!(
        r#"/**
 * Shared preview styles - generated by veneer.
 *
 * The rafters documentation sheet ({DOCUMENTATION_SHEET_PATH}), verbatim.
 * Every generated preview imports this module and adopts the sheet WHOLE
 * into its shadow root. The sheet carries its tokens on :host, so an adopted
 * copy overrides whatever theme the host page declares on :root -- a preview
 * renders as its designer intended regardless of where it is embedded.
 */

const previewCss = '{css}';

let previewSheet = null;

export function previewStyles() {{
  if (previewSheet === null) {{
    previewSheet = new CSSStyleSheet();
    previewSheet.replaceSync(previewCss);
  }}
  return previewSheet;
}}

export default previewStyles;
"#,
        css = escape_string(full_css),
    )
}

/// The import every generated preview module opens with.
fn stylesheet_js() -> String {
    format!("import {{ previewStyles }} from './{PREVIEW_STYLES_MODULE}';")
}

/// Generate a Web Component class from the extracted component structure.
/// CSS is delivered via `shadowRoot.adoptedStyleSheets` from the shared
/// [`PREVIEW_STYLES_MODULE`]; no page-global style is read or injected.
pub fn generate_web_component(tag_name: &str, structure: &ComponentStructure) -> String {
    let class_name = to_pascal_case(tag_name);

    let variant_entries: String = structure
        .variant_lookup
        .iter()
        .map(|(k, v)| format!("  {}: '{}',", k, escape_string(v)))
        .collect::<Vec<_>>()
        .join("\n");

    let size_entries: String = structure
        .size_lookup
        .iter()
        .map(|(k, v)| format!("  {}: '{}',", k, escape_string(v)))
        .collect::<Vec<_>>()
        .join("\n");

    let attrs_array: String = structure
        .observed_attributes
        .iter()
        .map(|a| format!("'{}'", a))
        .collect::<Vec<_>>()
        .join(", ");

    let default_variant = &structure.default_variant;
    let default_size = &structure.default_size;
    let base_classes = escape_string(&structure.base_classes);
    let disabled_classes = escape_string(&structure.disabled_classes);

    format!(
        r#"/**
 * {class_name} - Generated Web Component Preview
 * Auto-generated from {name} component
 * Tag: <{tag_name}>
 */

{stylesheet_js}

const variantClasses = {{
{variant_entries}
}};

const sizeClasses = {{
{size_entries}
}};

const baseClasses = '{base_classes}';
const disabledClasses = '{disabled_classes}';

export class {class_name} extends HTMLElement {{
  static observedAttributes = [{attrs_array}];

  #button = null;

  constructor() {{
    super();
    this.attachShadow({{ mode: 'open' }});
  }}

  connectedCallback() {{
    this.shadowRoot.adoptedStyleSheets = [previewStyles()];
    this.#render();
  }}

  attributeChangedCallback() {{
    this.#render();
  }}

  #render() {{
    if (!this.shadowRoot) return;

    const variant = this.getAttribute('variant') || '{default_variant}';
    const size = this.getAttribute('size') || '{default_size}';
    const disabled = this.hasAttribute('disabled');
    const loading = this.hasAttribute('loading');

    const isDisabled = disabled || loading;

    const classes = [
      baseClasses,
      variantClasses[variant] ?? variantClasses['{default_variant}'],
      sizeClasses[size] ?? sizeClasses['{default_size}'],
      isDisabled ? disabledClasses : '',
    ]
      .filter(Boolean)
      .join(' ');

    // Clear existing button if any
    if (this.#button) {{
      this.#button.remove();
    }}

    this.#button = document.createElement('button');
    this.#button.type = 'button';
    this.#button.className = classes;
    this.#button.disabled = isDisabled;

    if (isDisabled) {{
      this.#button.setAttribute('aria-disabled', 'true');
    }}
    if (loading) {{
      this.#button.setAttribute('aria-busy', 'true');
    }}

    if (loading) {{
      const span = document.createElement('span');
      span.setAttribute('aria-hidden', 'true');
      span.textContent = 'Loading...';
      this.#button.appendChild(span);
    }} else {{
      // Use slot for content
      const slot = document.createElement('slot');
      this.#button.appendChild(slot);
    }}

    this.shadowRoot.appendChild(this.#button);
  }}
}}

// Register the custom element
if (typeof customElements !== 'undefined') {{
  customElements.define('{tag_name}', {class_name});
}}

export default {class_name};
"#,
        class_name = class_name,
        name = structure.name,
        tag_name = tag_name,
        stylesheet_js = stylesheet_js(),
        variant_entries = variant_entries,
        size_entries = size_entries,
        base_classes = base_classes,
        disabled_classes = disabled_classes,
        attrs_array = attrs_array,
        default_variant = default_variant,
        default_size = default_size,
    )
}

/// Generate a passthrough Web Component that renders a slot with adopted styles.
///
/// Used for compound/structural components (Card, Accordion, Dialog, etc.) that
/// don't have variant/size switching but still need style isolation for previews.
/// The component renders its light DOM children inside a shadow root whose
/// `adoptedStyleSheets` carry the shared preview sheet — never page styles.
pub fn generate_passthrough_web_component(tag_name: &str) -> String {
    let class_name = to_pascal_case(tag_name);

    format!(
        r#"/**
 * {class_name} - Passthrough Web Component Preview
 * Auto-generated for static component preview
 * Tag: <{tag_name}>
 */

{stylesheet_js}

export class {class_name} extends HTMLElement {{
  constructor() {{
    super();
    this.attachShadow({{ mode: 'open' }});
  }}

  connectedCallback() {{
    this.shadowRoot.adoptedStyleSheets = [previewStyles()];
    this.#render();
  }}

  #render() {{
    if (!this.shadowRoot) return;
    const slot = document.createElement('slot');
    this.shadowRoot.appendChild(slot);
  }}
}}

if (typeof customElements !== 'undefined') {{
  customElements.define('{tag_name}', {class_name});
}}

export default {class_name};
"#,
        class_name = class_name,
        tag_name = tag_name,
        stylesheet_js = stylesheet_js(),
    )
}

/// Convert kebab-case to PascalCase.
fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Escape a string for JavaScript output.
fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn to_pascal_case_works() {
        assert_eq!(to_pascal_case("button-preview"), "ButtonPreview");
        assert_eq!(to_pascal_case("my-component"), "MyComponent");
        assert_eq!(to_pascal_case("simple"), "Simple");
    }

    #[test]
    fn escape_string_works() {
        assert_eq!(escape_string("hello"), "hello");
        assert_eq!(escape_string("it's"), "it\\'s");
        assert_eq!(escape_string("line1\nline2"), "line1\\nline2");
    }

    #[test]
    fn generates_valid_web_component() {
        let structure = ComponentStructure {
            name: "Button".to_string(),
            variant_lookup: vec![
                (
                    "primary".to_string(),
                    "bg-primary text-primary-foreground".to_string(),
                ),
                (
                    "secondary".to_string(),
                    "bg-secondary text-secondary-foreground".to_string(),
                ),
            ],
            size_lookup: vec![
                ("sm".to_string(), "h-8 px-3".to_string()),
                ("md".to_string(), "h-10 px-4".to_string()),
            ],
            base_classes: "inline-flex items-center".to_string(),
            disabled_classes: "opacity-50".to_string(),
            default_variant: "primary".to_string(),
            default_size: "md".to_string(),
            observed_attributes: vec!["variant".to_string(), "size".to_string()],
            dynamic_class_patterns: vec![],
        };

        let output = generate_web_component("my-button", &structure);

        assert!(output.contains("class MyButton extends HTMLElement"));
        assert!(output.contains("static observedAttributes"));
        assert!(output.contains("customElements.define('my-button'"));
        assert!(output.contains("bg-primary"));
        assert!(output.contains("adoptedStyleSheets"));
    }

    const SHEET: &str = ":host {\n  --color-primary: oklch(0.645 0.12 180);\n}\n\n.bg-primary {\n  background-color: var(--color-primary);\n}\n";

    /// The isolation contract, asserted structurally on the generated JS:
    /// CSS enters only through the shadow root, never the page.
    fn assert_style_isolated(js: &str) {
        // Open shadow root.
        assert!(
            js.contains("this.attachShadow({ mode: 'open' })"),
            "must attach an open shadow root"
        );
        // CSS delivered via adoptedStyleSheets on the shadow root, from the
        // ONE shared sheet module -- never a per-component copy.
        assert!(
            js.contains("this.shadowRoot.adoptedStyleSheets = [previewStyles()]"),
            "must adopt the shared preview sheet onto the shadow root"
        );
        assert!(
            js.contains("import { previewStyles } from './preview-styles.js';"),
            "must import the shared sheet rather than embedding one"
        );
        assert!(
            !js.contains("new CSSStyleSheet()"),
            "the sheet is constructed once in the shared module, not per component"
        );
        // Zero page-global style interaction: nothing read from or written
        // to the host document's styles.
        assert!(!js.contains("document.styleSheets"));
        assert!(!js.contains("document.head"));
        assert!(!js.contains("document.adoptedStyleSheets"));
        assert!(!js.contains("<style"));
        assert!(!js.contains("<link"));
        assert!(!js.contains("createElement('style')"));
        assert!(!js.contains("createElement('link')"));
        assert!(!js.contains("data-veneer-component"));
        // No framework runtime. The only import a preview carries is the
        // shared sheet module beside it.
        assert_eq!(
            js.matches("import ").count(),
            1,
            "the shared sheet import is the only import a preview may carry"
        );
        assert!(!js.contains("require("));
        assert!(!js.to_lowercase().contains("react"));
    }

    #[test]
    fn web_component_imports_the_shared_sheet_and_isolates_styles() {
        let structure = make_full_structure();
        let output = generate_web_component("button-preview", &structure);

        assert_style_isolated(&output);
        // The sheet text itself is NOT in the preview -- that is the point.
        assert!(!output.contains("background-color: var(--color-primary);"));
    }

    #[test]
    fn passthrough_web_component_imports_the_shared_sheet_and_isolates_styles() {
        let output = generate_passthrough_web_component("card-preview");

        assert_style_isolated(&output);
        assert!(output.contains("customElements.define('card-preview'"));
    }

    #[test]
    fn web_component_block_records_the_classes_it_resolves_to() {
        let structure = make_full_structure();
        let block = web_component_block("button-preview", &structure);

        assert_style_isolated(&block.web_component);
        assert_eq!(block.tag_name, "button-preview");
        assert!(block.classes_used.contains(&"bg-primary".to_string()));
    }

    #[test]
    fn preview_styles_module_carries_the_sheet_once_and_shares_one_stylesheet() {
        let module = preview_styles_module(SHEET);

        // The sheet arrives verbatim (JS-escaped), authored by rafters and
        // rewritten by nobody.
        assert!(module.contains("background-color: var(--color-primary);"));
        assert!(module.contains(":host {"));
        // One construction, memoized, exported for every preview to share.
        assert_eq!(module.matches("new CSSStyleSheet()").count(), 1);
        assert!(module.contains("export function previewStyles()"));
    }

    #[test]
    fn preview_block_renders_when_the_project_has_a_sheet() {
        let structure = make_full_structure();
        let block = preview_web_component_block("button-preview", &structure, SHEET)
            .expect("a non-empty sheet is all a preview needs");

        assert_style_isolated(&block.web_component);
    }

    #[test]
    fn preview_block_refuses_naming_component_and_path_on_a_missing_sheet() {
        let structure = make_full_structure();
        let error = preview_web_component_block("button-preview", &structure, "")
            .expect_err("no sheet means no preview");

        let message = error.to_string();
        assert!(
            message.contains("Button"),
            "the refusal must name the component: {message}"
        );
        assert!(
            message.contains(DOCUMENTATION_SHEET_PATH),
            "the refusal must name the path it looked for: {message}"
        );
        assert!(matches!(
            error,
            TransformError::RenderFailed { ref component, .. } if component == "Button"
        ));
    }

    #[test]
    fn preview_block_refuses_a_present_but_empty_sheet() {
        // Whitespace-only is the shape a broken regenerate leaves behind:
        // present, readable, and carrying nothing. Refused like absence,
        // because an unstyled preview reads as a design choice.
        let structure = make_full_structure();
        let error = preview_web_component_block("button-preview", &structure, "   \n\t\n")
            .expect_err("a blank sheet is not a sheet");
        assert!(error.to_string().contains("Button"));
    }

    fn make_full_structure() -> ComponentStructure {
        ComponentStructure {
            name: "Button".to_string(),
            variant_lookup: vec![
                ("primary".to_string(), "bg-primary".to_string()),
                ("secondary".to_string(), "bg-secondary".to_string()),
                ("destructive".to_string(), "bg-destructive".to_string()),
            ],
            size_lookup: vec![
                ("sm".to_string(), "h-8 px-3".to_string()),
                ("md".to_string(), "h-10 px-4".to_string()),
                ("lg".to_string(), "h-12 px-6".to_string()),
            ],
            base_classes: "inline-flex items-center".to_string(),
            disabled_classes: "opacity-50".to_string(),
            default_variant: "primary".to_string(),
            default_size: "md".to_string(),
            observed_attributes: vec![
                "variant".to_string(),
                "size".to_string(),
                "disabled".to_string(),
                "loading".to_string(),
            ],
            dynamic_class_patterns: vec![],
        }
    }
}
